# Generated by Django 4.2 on 2023-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("correo", models.CharField(max_length=200)),
                ("pregunta", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
